---
 - name: install package host1 host2
   yum:
     name:
        - postgresql14-server
        - patroni
        - python3
        - python3-etcd
        - etcd
        - postgresql14
        - postgresql14-contrib
        - patroni-etcd
        - haproxy
        - keepalived
        - python3-psycopg2
   delegate_to: "{{ item }}"
   with_items:
      - "{{ host1 }}"
      - "{{ host2 }}"

 - name: install package host3
   yum:
     name:
        - python3
        - python3-etcd
        - etcd
        - patroni-etcd
        - python3-psycopg2
   delegate_to: "{{ item }}"
   with_items:
     - "{{ host3 }}"
      

 - name: —Åreate directory host1 host2
   file:
     path: "{{ item }}"
     state: directory
   with_items:
     - '/etc/pki/tls/certetcd'
     - '/etc/patroni/'
     - '/srv/postgres/'

    
 - name: move cert
   ansible.builtin.shell:
     cmd: mv /home/yagudintr/* /etc/pki/tls/certetcd/
   ignore_errors: yes


